---

# mysql.yml
- name: Update pkgs
  apt: update_cache=yes

- name: Upgrade pkgs
  apt: upgrade=full

- name: Install debconf-utils
  apt: pkg=debconf-utils force=yes update_cache=yes

- name: Set MySQL root password
  shell: echo "mysql-server mysql-server/root_password password root" | debconf-set-selections

- name: Set MySQL root repassword
  shell: echo "mysql-server mysql-server/root_password_again password root" | debconf-set-selections 

- name: Install MySQL Server
  apt: pkg=mysql-server force=yes update_cache=yes

- name: Install MySQL Client
  apt: pkg=mysql-client force=yes update_cache=yes

