
# ruby.yml

- name: Update pkgs
  apt: update_cache=yes

- name: Upgrade pkgs
  apt: upgrade=full

- name: Install basic server pkgs
  apt: pkg={{ item }} force=yes update_cache=yes
  with_items:
    - build-essential
    - git
    - autoconf
    - bison
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev

- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git
       dest=~/.rbenv
  sudo: yes
  sudo_user: vagrant

- name: Install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build
  sudo: yes
  sudo_user: vagrant

- name: Install ruby (1.9.3-p547)
  shell: eval "$(~/.rbenv/bin/rbenv init -)" && ~/.rbenv/bin/rbenv install 1.9.3-p547 
  args:
    chdir: ~ 
    creates: ~/.rbenv/versions/1.9.3-p547/bin/ruby
  sudo: yes
  sudo_user: vagrant

#
# rbenv rehash
# rbenv global 1.9.3-p547



