
# ruby.yml

- name: Update pkgs
  apt: update_cache=yes

- name: Upgrade pkgs
  apt: upgrade=full

- name: Install basic server pkgs
  apt: pkg={{ item }} force=yes update_cache=yes
  with_items:
    - build-essential
    - git
    - autoconf
    - bison
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev

- name: Install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git
       dest=~/.rbenv
  sudo: yes
  sudo_user: vagrant

- name: Install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build
  sudo: yes
  sudo_user: vagrant

- name: Install ruby (1.9.3-p547)
  shell: eval "$(~/.rbenv/bin/rbenv init -)" && ~/.rbenv/bin/rbenv install 1.9.3-p547 && ~/.rbenv/bin/rbenv rehash && ~/.rbenv/bin/rbenv global 1.9.3-p547
  args:
    chdir: ~ 
    creates: ~/.rbenv/versions/1.9.3-p547/bin/ruby
  sudo: yes
  sudo_user: vagrant


- name: create ruby dict directory
  file: path=~/.vim/dict/ruby/1.9.3p547/ state=directory
  sudo: yes
  sudo_user: vagrant

- name: copy makedict.rb
  copy: src=./ruby/makedict.rb dest=/tmp/makedict.rb
  sudo: yes
  sudo_user: vagrant

- name: Install rubydict
  shell: ~/.rbenv/shims/ruby /tmp/makedict.rb ~/.rbenv/versions/1.9.3-p547  >  ~/.vim/dict/ruby/1.9.3p547/ruby.dict
  sudo: yes
  sudo_user: vagrant





